apiVersion: v1
kind: Template
metadata:
  name: istio-removal-job
parameters:
- displayName: OpenShift Release
  description: The version of the OpenShift release.
  name: OPENSHIFT_RELEASE
  value: v3.9.0
  required: true
- displayName: OpenShift Deployment Type
  description: The OpenShift deployment type, either origin or openshift-enterprise
  name: OPENSHIFT_DEPLOYMENT_TYPE
  value: origin
  required: true
- displayName: Istio Image Prefix
  description: The prefix for the Istio images
  name: OPENSHIFT_ISTIO_IMAGE_PREFIX
  value: docker.io/openshiftistio/
- displayName: Istio Image Version
  description: The version of the Istio images
  name: OPENSHIFT_ISTIO_IMAGE_VERSION
  value: "0.8.0"
- displayName: Istio Namespace
  description: The namespace for the Istio components
  name: OPENSHIFT_ISTIO_NAMESPACE
  value: istio-system
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: removal.istio.inventory
    namespace: ${OPENSHIFT_ISTIO_NAMESPACE}
  data: 
    istio.inventory: |-
      [OSEv3:children]
      masters
      
      [OSEv3:vars]
      openshift_release=${OPENSHIFT_RELEASE}
      openshift_istio_install=false
      
      openshift_istio_oc_token=true
      
      [masters]
      127.0.0.1 ansible_connection=local
- apiVersion: batch/v1
  kind: Job
  metadata:
    labels:
      job-name: openshift-ansible-istio-removal-job
    name: openshift-ansible-istio-removal-job
    namespace: ${OPENSHIFT_ISTIO_NAMESPACE}
  spec:
    backoffLimit: 6
    completions: 1
    parallelism: 1
    template:
      metadata:
        labels:
          job-name: openshift-ansible-istio-removal-job
      spec:
        containers:
        - env:
          - name: INVENTORY_FILE
            value: /tmp/inventory/istio.inventory
          - name: PLAYBOOK_FILE
            value: playbooks/openshift-istio/config.yml
          - name: OPTS
            value: -vvv
          image: ${OPENSHIFT_ISTIO_IMAGE_PREFIX}${OPENSHIFT_DEPLOYMENT_TYPE}-ansible:${OPENSHIFT_ISTIO_IMAGE_VERSION}
          imagePullPolicy: IfNotPresent
          name: openshift-ansible-istio-removal-job
          securityContext:
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/origin/master
            name: configdir
          - mountPath: /tmp/inventory
            name: configmap
        dnsPolicy: ClusterFirst
        hostNetwork: true
        restartPolicy: Never
        schedulerName: default-scheduler
        serviceAccount: openshift-ansible
        serviceAccountName: openshift-ansible
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /etc/origin/master
          name: configdir
        - name: configmap
          configMap:
            name: removal.istio.inventory
